info:
  app:
    name: Monolitihic
    description: Monolitihic - Application - All in one ;)

server:
  port: 8080
  
management:
  cloudfoundry:
    skip-ssl-validation: true
  info:
    git:
      mode: full

  
  
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    com.idugalic: DEBUG
    com.atomist.spring.agent: DEBUG

authserver:
  hostname: localhost
  port: 9999
  contextPath: uaa


      
security:
  oauth2:
    resource:
      jwt:
        keyUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      
flyway:
  locations: db/migration/h2
atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/T03LLQPNQ'
  environment:
    domain: '${vcap.application.application_name:development}'
    pod: '${vcap.application.application_name:${random.value}}'
---
spring:
  profiles: cloud
  jpa:
    database:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${vcap.services.mysql.credentials.jdbcUrl}
    username: ${vcap.services.mysql.credentials.username}
    password: ${vcap.services.mysql.credentials.password}
    
flyway:
  locations: db/migration/mysql

