CREATE SEQUENCE SYSTEM_SEQUENCE_4277C43D_4C4B_4DDD_B4F6_AA9A219E2A9F START WITH 1 BELONGS_TO_TABLE;
DROP TABLE IF EXISTS `APP_USER`;
CREATE TABLE APP_USER(
    ID BIGINT DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_4277C43D_4C4B_4DDD_B4F6_AA9A219E2A9F) NOT NULL NULL_TO_DEFAULT SEQUENCE SYSTEM_SEQUENCE_4277C43D_4C4B_4DDD_B4F6_AA9A219E2A9F,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    USERNAME VARCHAR(255)
);
ALTER TABLE APP_USER ADD CONSTRAINT CONSTRAINT_76 PRIMARY KEY(ID);


CREATE SEQUENCE SYSTEM_SEQUENCE_31D925E7_A7FE_45C9_832A_F1C626FA118C START WITH 1 BELONGS_TO_TABLE;
DROP TABLE IF EXISTS `APP_ROLE`;
CREATE TABLE APP_ROLE(
    ID BIGINT DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_31D925E7_A7FE_45C9_832A_F1C626FA118C) NOT NULL NULL_TO_DEFAULT SEQUENCE SYSTEM_SEQUENCE_31D925E7_A7FE_45C9_832A_F1C626FA118C,
    DESCRIPTION VARCHAR(255),
    ROLE_NAME VARCHAR(255)
);
ALTER TABLE APP_ROLE ADD CONSTRAINT CONSTRAINT_77 PRIMARY KEY(ID);

DROP TABLE IF EXISTS `USER_ROLE`;
CREATE TABLE USER_ROLE(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);
ALTER TABLE USER_ROLE ADD CONSTRAINT FKG7FR1R7O0FKK41NFHNJDYQN7B FOREIGN KEY(USER_ID) REFERENCES APP_USER(ID) NOCHECK;
ALTER TABLE USER_ROLE ADD CONSTRAINT FKP6M37G6N6C288S096400UW8FW FOREIGN KEY(ROLE_ID) REFERENCES APP_ROLE(ID) NOCHECK;



-- INITIAL DATA
INSERT INTO app_role (id, role_name, description) VALUES (1, 'STANDARD_USER', 'Standard User - Has no admin rights');
INSERT INTO app_role (id, role_name, description) VALUES (2, 'ADMIN_USER', 'Admin User - Has permission to perform admin tasks');

INSERT INTO app_user (id, first_name, last_name, password, username) VALUES (1, 'John', 'Doe', '{noop}jwtpass', 'john.doe');
INSERT INTO app_user (id, first_name, last_name, password, username) VALUES (2, 'Admin', 'Admin', '{noop}jwtpass', 'admin.admin');

INSERT INTO user_role(user_id, role_id) VALUES(1,1);
INSERT INTO user_role(user_id, role_id) VALUES(2,1);
INSERT INTO user_role(user_id, role_id) VALUES(2,2);
